-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "maxPlayers" INTEGER,
ADD COLUMN     "maxTime" INTEGER,
ADD COLUMN     "minAge" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "minPlayers" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "minTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rating" DOUBLE PRECISION NOT NULL DEFAULT 0;
